runtime: python39
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  BASIC_AUTH_USERNAME='njitbytes'
  BASIC_AUTH_PASSWORD='hacknjit2019'

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
